[package]
name = "star_realms"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
# this is the development version of Yew
yew = { git = "https://github.com/yewstack/yew/", features = ["csr", ] }
web-sys = { version = "0.3", features = ["Event"] }
wasm-logger = "0.2"
log = "0.4"